---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudtechie/pcfclis
inputs:
  - name: pcf-tools
outputs:
  - name: aws_access_json
params:
  aws_access_key_id:
  aws_secret_access_key:
  aws_region:
  aws_iam_user_name:
run:
  path: pcf-tools/pipelines/tasks/create-iam-user/task.sh
