---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudtechie/pcfclis
outputs:
  - name: bbl-output
params:
  aws_access_key_id:
  aws_secret_access_key:
  aws_region:
  aws_iam_user_name:
run:
  path: tasks/install-bosh/task.sh
