---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudtechie/pcfclis
inputs:
  - name: aws_access_json
outputs:
  - name: bbl-env
params:
  aws_access_key_id:
  aws_secret_access_key:
  aws_region:
run:
  path: pcf-tools/pipelines/tasks/install-bosh-with-bbl/task.sh
